name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # actions that clone repo
      - name: Use Node.js
        uses: actions/setup-node@v3 # action to setup nodejs
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

